volumes:
  nextcloud:
  db:
services:
  collabora_code:
    image: collabora/code:latest
    container_name: collabora
    restart: unless-stopped
    #user: root
    cap_add:
      - MKNOD
    ports:
      - 9980:9980
    environment:
      - password=lnsy_21our
      - username=admin
      - domain=218\.25\.37\.251
      - "extra_params=--o:ssl.enable=false"
  db:
    image: mariadb:10.6
    container_name: db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --skip-innodb-read-only-compressed
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=lnsy_21our
      - MYSQL_PASSWORD=lnsy_21our
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: app
    restart: always
    ports:
      - 9080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=lnsy_21our
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
